# Generated by Django 4.2.4 on 2023-08-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cooking_time', models.PositiveIntegerField()),
                ('difficulty', models.CharField(max_length=20)),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='recipes.ingredient')),
            ],
        ),
    ]
