# Generated by Django 4.2.4 on 2023-09-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredient_name'),
        ('recipesingredients', '0001_initial'),
        ('recipes', '0008_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipesingredients.RecipeIngredient', to='ingredients.ingredient'),
        ),
    ]
