# Generated by Django 4.2.4 on 2023-09-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(default='no_image.jpg', upload_to='recipes'),
        ),
    ]
