# Generated by Django 4.2.4 on 2023-09-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipe_description_alter_recipe_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default="this recipe doesn't have a description"),
        ),
    ]
